import { DM_Sans } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";
import { LanguageProvider } from "@/components/LanguageProvider";
import ReduxProvider from "@/components/ReduxProvider";
// import AOSProvider from "@/components/AosProvider";

const DMSans = DM_Sans({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

// export const metadata = {
//   title: "Techincal test",
//   description: "Generated by create next app",
// };
export const metadata = {
  metadataBase: new URL("https://muhammad-bin-hindi-law-firm.vercel.app/"),
  title: {
    default: "Techincal test",
    template: "%s | Law Firm",
  },
  description:
    "Leading legal office offering exceptional advisory services for individuals and companies",
  keywords: ["legal services", "law firm", "consultation", "legal advice"],
  authors: [{ name: "Law Firm" }],
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://muhammad-bin-hindi-law-firm.vercel.app/",
    title: "Law Firm",
    description: "Expert Legal Services",
    siteName: "Law Firm",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default async function RootLayout({ children }) {
  return (
    <html>
      <body className={`${DMSans.variable} antialiased`}>
        <ReduxProvider>
          <LanguageProvider>
            {/* <AOSProvider> */}
            <Navbar />
            {children}
            <Footer />
            {/* </AOSProvider> */}
          </LanguageProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
