import { DM_Sans } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";
import { LanguageProvider } from "@/components/LanguageProvider";
// import ReduxProvider from "@/components/ReduxProvider";

const DMSans = DM_Sans({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

export const metadata = {
  title: "Techincal test",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html>
      <body className={`${DMSans.variable} antialiased`}>
        {/* <ReduxProvider> */}
          <LanguageProvider>
            <Navbar />
            {children}
            <Footer />
          </LanguageProvider>
        {/* </ReduxProvider> */}
      </body>
    </html>
  );
}
